language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
install:
 # install Python dependencies
 - pip install --upgrade pip
 - "pip install -e .[tests]"
 - pip install python-coveralls
 # install Node dependencies
 - npm install mocha gulp
 - npm install
 - export PATH=$PATH:/usr/lib/node_modules/.bin/
script:
 - flake8
 - nosetests -vv --with-coverage --cover-package=databench --cover-erase
after_success:
 - coveralls || true
 - bash <(curl -s https://codecov.io/bash)
