language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
install:
 - "pip install --upgrade pip"
 - "pip install -e .[tests]"
 - "pip install python-coveralls coverage"
 - "npm install -g mocha gulp"
script: "nosetests -vv --with-coverage --cover-package=databench --cover-erase"
after_success:
  - coveralls
